defaults: &defaults
  google_client_id:   go_to_google_dev_console_add_new_app
  google_secret:      and_paste_config_here
  google_domain:      fill_in_your_domain
  github_client_id:   go_to_github_settings_and_add_new_app
  github_secret:      and_paste_config_here
  api_token:          miamiamia
  secret_token_key:   miaaaaamia
  company_name:       Company
  calendar_id:               xxxx@group.calendar.google.com
  calendar_summary_regex: vacation|urlop|holiday|wyjazd|wakacje
  emails:
    from:             default_address_used_to_send_emails
    pm:               pms_email_address
    support:          support
    internal:         example.com
    social:           example.com
    notifications:
      changes_digest:
        days:         30
        weekday:      monday
  hipchat:
    active:           false
    api_token:        your_hipchat_api_token
    author_name:      name_for_message_author
    notify_users:     true
    message_color:    yellow
    room_name:        room_where_to_send_notifications
  tld_length:         1
  feature:
    new_available_view: false
  rollbar:
    access_token:     token

heroku_settings: &heroku_settings
  <<: *defaults
  github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_secret:    <%= ENV['GITHUB_CLIENT_SECRET'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_secret:    <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  google_domain:    <%= ENV['GOOGLE_DOMAIN'] %>
  api_token:        <%= ENV['API_TOKEN'] %>
  secret_token_key: <%= ENV['SECRET_TOKEN_KEY'] %>
  sendgrid:
    login:          <%= ENV['SENDGRID_USERNAME'] %>
    password:       <%= ENV['SENDGRID_PASSWORD'] %>
    domain:         <%= ENV['SENDGRID_DOMAIN'] %>
  emails:
    from:             <%= ENV['EMAIL_FROM'] %>
    pm:               <%= ENV['EMAIL_PM'] %>
    internal:         <%= ENV['EMAIL_INTERNAL'] %>
    social:           <%= ENV['EMAIL_SOCIAL'] %>
    support:          <%= ENV['EMAIL_SUPPORT'] %>
  hipchat:
    active:           <%= ENV['HIPCHAT_ACTIVE'] %>
    api_token:        <%= ENV['HIPCHAT_API_TOKEN'] %>
    author_name:      <%= ENV['HIPCHAT_AUTHOR_NAME'] %>
    notify_users:     <%= ENV['HIPCHAT_NOTIFY_USERS'] %>
    message_color:    <%= ENV['HIPCHAT_MESSAGE_COLOR'] %>
    room_name:        <%= ENV['HIPCHAT_ROOM_NAME'] %>
  company_name:       <%= ENV['COMPANY_NAME'] %>
  domain:             <%= ENV['DOMAIN'] %>
  tld_length:         <%= ENV['TLD_LENGTH'] %>
  feature:
    new_available_view: <%= ENV['AVAILABLE_VIEW'] %>

development:
  <<: *defaults
  domain: people.dev
  feature:
    new_available_view: true

test:
  <<: *defaults
  domain: people.test
  hipchat:
    active: false
    api_token: 1234567890

staging:
  <<: *heroku_settings

production:
  <<: *heroku_settings
